import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();
  if (isLoading) return <div> Test change </div>;

  if (!data) return <div> Something went wrong</div>;
  console.log;

  return (
    <>
      <Head>
        <title>yolked</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 flex justify-center">
        <div className="flex w-full justify-end border-b border-slate-400 p-8">
          {!user.isSignedIn && (
            <div className="">
              <SignInButton />
            </div>
          )}
          {user.isSignedIn && (
            <div className="">
              <SignOutButton />
            </div>
          )}
        </div>
      </header>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400  md:max-w-4xl">
          {/* <div className="flex flex-col bg-blue-400">
            {[...data, ...data]?.map((post) => (
              <div key={post.id} className="border-b border-slate-400 p-8">
                {post.content}
              </div>
            ))}
          </div> */}
          <div className="flex h-full justify-center">
            <div className="flex flex-col p-4 text-center">
              <ul>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Monday
                </li>
                <li className="mb-3 flex cursor-move items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Bench
                </li>
                <li className="mb-3 flex cursor-move items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Squat
                </li>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-400 p-4 shadow">
                  +
                </li>
              </ul>
            </div>
            <div className="flex flex-col p-4 text-center">
              <ul>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Tuesday
                </li>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-400 p-4 shadow">
                  +
                </li>
              </ul>
            </div>
            <div className="flex flex-col p-4 text-center">
              <ul>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Wednesday
                </li>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-400 p-4 shadow">
                  +
                </li>
              </ul>
            </div>
            <div className="flex flex-col p-4 text-center">
              <ul>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Thursday
                </li>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-400 p-4 shadow">
                  +
                </li>
              </ul>
            </div>
            <div className="flex flex-col p-4 text-center">
              <ul>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Friday
                </li>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-400 p-4 shadow">
                  +
                </li>
              </ul>
            </div>
            <div className="flex flex-col p-4 text-center">
              <ul>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Saturday
                </li>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-400 p-4 shadow">
                  +
                </li>
              </ul>
            </div>
            <div className="flex flex-col p-4 text-center">
              <ul>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-600 p-4 shadow">
                  Sunday
                </li>
                <li className="mb-3 flex items-center justify-between rounded-lg bg-slate-400 p-4 text-center">
                  +
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
