import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();
  if (isLoading) return <div> Loading ...</div>;

  if (!data) return <div> Something went wrong</div>;
  console.log;

  return (
    <>
      <Head>
        <title>yolked</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 flex justify-center bg-white">
        <div className="flex w-full justify-end border-b border-slate-400 bg-fuchsia-400 p-8">
          {!user.isSignedIn && (
            <div className="">
              <SignInButton />
            </div>
          )}
          {user.isSignedIn && (
            <div className="">
              <SignOutButton />
            </div>
          )}
        </div>
      </header>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 bg-blue-900 md:max-w-4xl">
          {/* <div className="flex flex-col bg-blue-400">
            {[...data, ...data]?.map((post) => (
              <div key={post.id} className="border-b border-slate-400 p-8">
                {post.content}
              </div>
            ))}
          </div> */}
          <div className="flex h-full flex-col justify-center bg-red-600">
            <div className="mx-auto columns-7 bg-red-400">
              {/* <button className="w-full rounded-lg font-bold uppercase">
                Get started
              </button> */}
              <h1>Monday</h1>
              <h1>Monday</h1>
              <h1>Monday</h1>
              <h1>Monday</h1>
              <h1>Monday</h1>
              <h1>Monday</h1>
              <h1>Monday</h1>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
